name: Execute Tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests'
        required: true
        type: string
        default: 'QA'

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Install dependencies
        run: |
          npm ci
          npm i -D @playwright/test
          npx playwright install chromium
          
      - name: Run tests for ${{ inputs.environment }}
        run: |
          TEST_ENV=${{ inputs.environment }} npx playwright test tests/website.spec.ts || true
          
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ inputs.environment }}
          path: playwright-report.json
